# Generated by Django 2.2.7 on 2019-12-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STT', models.IntegerField()),
                ('Question', models.TextField()),
                ('A', models.CharField(max_length=5000)),
                ('B', models.CharField(max_length=5000)),
                ('C', models.CharField(max_length=5000)),
                ('D', models.CharField(max_length=5000)),
                ('Answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='THPTQG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Question', models.TextField()),
                ('A', models.CharField(max_length=5000)),
                ('B', models.CharField(max_length=5000)),
                ('C', models.CharField(max_length=5000)),
                ('D', models.CharField(max_length=5000)),
                ('Answer', models.CharField(max_length=1)),
            ],
        ),
    ]
