# Generated by Django 3.0 on 2019-12-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='THPTQG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STT', models.IntegerField()),
                ('Question', models.TextField()),
                ('A', models.CharField(max_length=5000)),
                ('B', models.CharField(max_length=5000)),
                ('C', models.CharField(max_length=5000)),
                ('D', models.CharField(max_length=5000)),
                ('Answer', models.CharField(max_length=1)),
            ],
        ),
    ]
