# Generated by Django 3.0 on 2019-12-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_thptqg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LOP10',
        ),
    ]
